// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAylG1RYAPR981xvqcBoxNn_YIvuvyKENk',
    appId: '1:495475729075:web:05c2f1a7671073a64846c6',
    messagingSenderId: '495475729075',
    projectId: 'nomadmate',
    authDomain: 'nomadmate.firebaseapp.com',
    storageBucket: 'nomadmate.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX9uIBYKJ-WQ7GJQN6nzyeAA9Pv1vUFHo',
    appId: '1:495475729075:android:b244dcbf790c47ef4846c6',
    messagingSenderId: '495475729075',
    projectId: 'nomadmate',
    storageBucket: 'nomadmate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQuTbg787nWRNzWjI5iHsi6KUNp1we6EI',
    appId: '1:495475729075:ios:e3be85a6b1bd8f384846c6',
    messagingSenderId: '495475729075',
    projectId: 'nomadmate',
    storageBucket: 'nomadmate.appspot.com',
    iosClientId: '495475729075-s7gqi46suf3l4goj7nk2j8ejccrbege2.apps.googleusercontent.com',
    iosBundleId: 'com.example.hanstour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQuTbg787nWRNzWjI5iHsi6KUNp1we6EI',
    appId: '1:495475729075:ios:38c83b70eb1ce0124846c6',
    messagingSenderId: '495475729075',
    projectId: 'nomadmate',
    storageBucket: 'nomadmate.appspot.com',
    iosClientId: '495475729075-pajt43v2j20nh2gtbgtguec518bf5tr5.apps.googleusercontent.com',
    iosBundleId: 'com.example.hanstour.RunnerTests',
  );
}
